services:
    twig.extension.array:
        class: Twig_Extensions_Extension_Array
        tags:
            - { name: twig.extension }

    innova_user.registration.form.type:
        class: Innova\SelfBundle\Form\UserType
        arguments:
            class: %fos_user.model.user.class%
            om: @doctrine.orm.entity_manager
        tags:
            - { name: form.type, alias: innova_selfbundle_user }

    innova_import:
        class: Innova\SelfBundle\Controller\ImportController
        arguments: 
            kernelRoot: %kernel.root_dir%
            entityManager: @doctrine.orm.entity_manager
